# Generated by Django 6.1 on 2026-08-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamprofile',
            name='average_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='library_played_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='recent_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='total_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
