# Generated by Django 6.1 on 2026-08-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_steamprofile_average_hours_steamprofile_games_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamprofile',
            name='stats_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
