# Generated by Django 6.1 on 2026-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_steamprofile_stats_initialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamprofile',
            name='achievements_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steamprofile',
            name='total_achievements',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
